# Generated by Django 4.1.5 on 2023-01-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_calorie_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='calorie_goal',
            field=models.DecimalField(blank=True, decimal_places=2, default=2000.0, max_digits=6),
        ),
    ]
