# Generated by Django 4.1.5 on 2023-01-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_eaten',
            name='meal',
            field=models.CharField(choices=[('صبحانه', 'صبحانه'), ('نهار', 'نهار'), ('شام', 'شام')], max_length=50),
        ),
        migrations.AlterField(
            model_name='food_eaten',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.fooditem'),
        ),
    ]
