# Generated by Django 4.1.5 on 2023-01-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_food_eaten_meal_alter_food_eaten_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_eaten',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.fooditem'),
        ),
    ]
